name: Sync with AWS CodeCommit

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Sync with AWS CodeCommit
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git remote add aws https://git-codecommit.us-east-2.amazonaws.com/v1/repos/test-github-sync
        git fetch aws
        if git show-ref --quiet refs/remotes/aws/main; then
          echo "Main branch exists in AWS CodeCommit. Pushing changes..."
          git push aws main
        else
          echo "Main branch does not exist in AWS CodeCommit. Creating and pushing changes..."
          git push aws HEAD:main
        fi
